# Generated by Django 4.1.7 on 2023-02-23 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='ID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='ID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='ID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='ID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='ID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='ID',
            new_name='id',
        ),
    ]
