# Generated by Django 4.1.7 on 2023-03-15 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0005_color_order_products_alter_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
